name: Release

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '23 19 * * *'
  workflow_dispatch:
    inputs:
      make_release:
        description: '是否创建 Release'
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        description: "选择 KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "选择 ksu 分支"
        required: true
        type: choice
        options:
          - Stable(标准)
          - Dev(开发)
          - Other(其他/指定)
        default: Dev(开发)
      version:
        description: '自定义版本号'
        required: false
        type: string
      use_zram:
        description: '是否开启 ZRAM'
        required: true
        type: boolean
        default: true
      use_bbg:
        description: '是否开启 BBG'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: '是否开启 KPM'
        required: true
        type: boolean
        default: false
      get_manager:
        description: '是否获取最新管理器'
        required: true
        type: boolean
        default: true
      onlyAk3:
        description: '仅上传 AK3 压缩包'
        required: true
        type: boolean
        default: true

# -----------------------------
# 所有 Job 构建
# -----------------------------
jobs:
  get_manager:
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'SukiSU' }}

  build-kernel-a12-5-10:
    uses: ./.github/workflows/kernel-a12-5.10.yml
    secrets: inherit
    with:
      make_release: true
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
      use_bbg: ${{ inputs.use_bbg }}
      onlyAk3: ${{ inputs.onlyAk3 || false }}


# -----------------------------
# Release 发布
# -----------------------------
  trigger-release:
    runs-on: ubuntu-latest
    needs:
      - get_manager
      - build-kernel-a12-5-10
    if: ${{ inputs.make_release }}
    env:
      REPO_OWNER: rosenii
      REPO_NAME: GKI_KernelSU_SUSFS
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      RELEASE_NAME: "GKI内核: ${{ inputs.kernelsu_variant }} & SUSFS ${{ needs.get_manager.outputs.ksuVer }}"
      RELEASE_TAG: "dev-${{ github.run_number }}"
      RELEASE_NOTES: |
        功能:
        -> KernelSU ${{ inputs.kernelsu_variant }}
        -> SUSFS ${{ needs.get_manager.outputs.susVer }}
        -> BBG ${{ inputs.use_bbg && '支持' || '不支持' }}
        -> ZRAM ${{ inputs.use_zram && '开启' || '未开启' }}
        -> KPM ${{ inputs.use_kpm && '支持' || '未支持' }}
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 下载所有 job 构建产物
      - name: Download get_manager artifacts
        uses: actions/download-artifact@v4
        with:
          name: manager-artifacts
          path: ./downloaded-artifacts/manager
          skip-decompression: true

      - name: Download kernel artifacts
        uses: actions/download-artifact@v4
        with:
          name: kernel-artifacts
          path: ./downloaded-artifacts/kernel
          skip-decompression: true

      # 创建 Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_NAME }}
          body: ${{ env.RELEASE_NOTES }}
          prerelease: true

      # 上传 get_manager 文件
      - name: Upload manager artifacts
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          shopt -s nullglob
          for f in ./downloaded-artifacts/manager/*; do
            echo "Uploading $f..."
            gh release upload "${RELEASE_TAG}" "$f" --clobber
          done

      # 上传 kernel 构建文件
      - name: Upload kernel artifacts
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          shopt -s nullglob
          for f in ./downloaded-artifacts/kernel/*; do
            echo "Uploading $f..."
            gh release upload "${RELEASE_TAG}" "$f" --clobber
          done
